using System.Text;
using Microsoft.CodeAnalysis;

namespace Cantrip.ApiDoc;

/// <summary>The Markdown itself.</summary>
public static class Render
{
    private const string Generated =
        "<!-- Generated by tools/Cantrip.ApiDoc from the XML documentation comments. Do not edit: run tools/api-docs.sh. -->";

    /// <summary>
    /// One line saying what each namespace is for. It is written here rather than read from the
    /// sources because a namespace has nowhere to carry a documentation comment, and because these
    /// nine lines change about as often as the namespaces do.
    /// </summary>
    private static readonly Dictionary<string, string> Blurbs = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["Cantrip"] = "The way in, and the values everything else is written in: `CardRuntime`, `ActionResult`, `Num`.",
        ["Cantrip.Content"] = "Loading `.cantrip` files: the library a game hands the runtime, and the definitions in it.",
        ["Cantrip.Descriptions"] = "Rules text: what a card says, worked out from what it does, through a phrase table a game can translate.",
        ["Cantrip.Diagnostics"] = "What a tool says about content it has not run: a code, a place and a fix.",
        ["Cantrip.Linting"] = "The linter, and every diagnostic code it can report, each as a named constant.",
        ["Cantrip.Runtime"] = "The rules themselves: entities, the board, events, modifiers, the clock, the interpreter and the snapshot.",
        ["Cantrip.Syntax"] = "The syntax tree the parser builds. A game never touches it; a tool that reads content lives in it.",
        ["Cantrip.Testing"] = "Running the `test` blocks written in content.",
    };

    private static string Blurb(ApiNamespace ns) =>
        Blurbs.TryGetValue(ns.Name, out string? blurb) ? blurb : ns.Set.Blurb;

    public static string Namespace(ApiNamespace ns)
    {
        var page = new StringBuilder();
        page.Append(Generated).Append("\n\n");
        page.Append("# ").Append(ns.Name).Append("\n\n");
        page.Append(Blurb(ns)).Append("\n\n");
        page.Append("Part of [the API reference](README.md). ");
        page.Append("The guides are [docs/csharp.md](../csharp.md) and [docs/godot.md](../godot.md); ");
        page.Append("when something here surprises you, [docs/troubleshooting.md](../troubleshooting.md) is the other end of it.\n\n");

        page.Append("| Type | |\n|---|---|\n");
        foreach (ApiType type in ns.Types)
        {
            page.Append("| [`").Append(type.Title).Append("`](#").Append(type.Anchor).Append(") | ");
            page.Append(OneLine(type.Docs.Summary)).Append(" |\n");
        }

        page.Append('\n');

        foreach (ApiType type in ns.Types)
        {
            page.Append("---\n\n");
            Type(type, page);
        }

        return page.ToString();
    }

    private static void Type(ApiType type, StringBuilder page)
    {
        page.Append("## ").Append(type.Title).Append("\n\n");
        page.Append("```csharp\n").Append(type.Declaration).Append("\n```\n\n");

        if (type.Docs.HasSummary) page.Append(type.Docs.Summary).Append("\n\n");
        else page.Append("*Undocumented.*\n\n");

        if (type.Docs.TypeParameters.Count > 0) Named("Type parameters", type.Docs.TypeParameters, page);
        if (type.Docs.Remarks.Length > 0) page.Append(type.Docs.Remarks).Append("\n\n");
        if (type.Docs.Example.Length > 0) page.Append("**Example.** ").Append(type.Docs.Example).Append("\n\n");

        if (type.Members.Count == 0) return;

        if (type.Symbol.TypeKind == TypeKind.Enum)
        {
            page.Append("| Member | |\n|---|---|\n");
            foreach (ApiMember member in type.Members)
            {
                page.Append("| `").Append(member.Declaration).Append("` | ");
                page.Append(OneLine(member.Docs.Summary)).Append(" |\n");
            }

            page.Append('\n');
            return;
        }

        int group = -1;
        foreach (ApiMember member in type.Members)
        {
            if (member.Group != group)
            {
                group = member.Group;
                page.Append("### ").Append(GroupName(group)).Append("\n\n");
            }

            Member(member, page);
        }
    }

    private static void Member(ApiMember member, StringBuilder page)
    {
        page.Append("```csharp\n").Append(member.Declaration).Append("\n```\n\n");

        if (member.Docs.HasSummary) page.Append(member.Docs.Summary).Append("\n\n");
        else page.Append("*Undocumented.*\n\n");

        if (member.Docs.TypeParameters.Count > 0) Named("Type parameters", member.Docs.TypeParameters, page);
        if (member.Docs.Parameters.Count > 0) Named("Parameters", member.Docs.Parameters, page);
        if (member.Docs.Returns.Length > 0) page.Append("**Returns.** ").Append(OneLine(member.Docs.Returns)).Append("\n\n");
        if (member.Docs.Value.Length > 0) page.Append("**Value.** ").Append(OneLine(member.Docs.Value)).Append("\n\n");
        if (member.Docs.Exceptions.Count > 0) Named("Throws", member.Docs.Exceptions, page);
        if (member.Docs.Remarks.Length > 0) page.Append(member.Docs.Remarks).Append("\n\n");
        if (member.Docs.Example.Length > 0) page.Append("**Example.** ").Append(member.Docs.Example).Append("\n\n");
    }

    private static void Named(string heading, List<(string Name, string Text)> entries, StringBuilder page)
    {
        page.Append("**").Append(heading).Append(".**\n\n");
        foreach ((string name, string text) in entries)
        {
            page.Append("- `").Append(name).Append('`');
            if (text.Length > 0) page.Append(" — ").Append(OneLine(text));
            page.Append('\n');
        }

        page.Append('\n');
    }

    private static string GroupName(int group) => group switch
    {
        0 => "Constructors",
        1 => "Fields and constants",
        2 => "Properties",
        3 => "Methods",
        4 => "Operators and conversions",
        5 => "Events",
        _ => "Other",
    };

    public static string Index(List<IndexEntry> entries, Coverage coverage)
    {
        var page = new StringBuilder();
        page.Append(Generated).Append("\n\n");
        page.Append("# API reference\n\n");
        page.Append("Every public type and member of `Cantrip.Core` and of the Godot addon's runtime scripts, ");
        page.Append("generated from the XML documentation comments in the sources.\n\n");

        page.Append("This is the reference. The guides are the place to start: ");
        page.Append("[docs/csharp.md](../csharp.md) for a game written in C#, [docs/godot.md](../godot.md) for the Godot node, ");
        page.Append("[docs/language.md](../language.md) for the content language, and ");
        page.Append("[docs/troubleshooting.md](../troubleshooting.md) when something has gone wrong.\n\n");

        page.Append("Nothing here is written by hand. `tools/api-docs.sh` regenerates it and CI runs ");
        page.Append("`tools/api-docs.sh --check`, so a member that changes its signature or its documentation ");
        page.Append("without this directory changing with it fails the build.\n\n");

        page.Append("## Pages\n\n");
        page.Append("| Namespace | Types | Documented | |\n|---|---:|---:|---|\n");

        foreach (IndexEntry entry in entries)
        {
            Coverage own = entry.Namespace.Coverage;
            page.Append("| [`").Append(entry.Namespace.Name).Append("`](").Append(entry.Namespace.Name).Append(".md) | ");
            page.Append(entry.Namespace.Types.Count).Append(" | ");
            page.Append(Coverage.Percent(own.Documented, own.Total)).Append(" | ");
            page.Append(Blurb(entry.Namespace)).Append(" |\n");
        }

        page.Append('\n');

        page.Append("## What is documented\n\n");
        page.Append("A member counts as documented when it has a `<summary>`. These numbers are the state of the ");
        page.Append("sources, not a target, and they are printed here because a reference that is half `*Undocumented.*` ");
        page.Append("should say so on its front page rather than make you find out one page at a time.\n\n");

        page.Append("| | Documented | Total | |\n|---|---:|---:|---:|\n");
        page.Append("| Types | ").Append(coverage.DocumentedTypes).Append(" | ").Append(coverage.Types)
            .Append(" | ").Append(Coverage.Percent(coverage.DocumentedTypes, coverage.Types)).Append(" |\n");
        page.Append("| Members | ").Append(coverage.DocumentedMembers).Append(" | ").Append(coverage.Members)
            .Append(" | ").Append(Coverage.Percent(coverage.DocumentedMembers, coverage.Members)).Append(" |\n");
        page.Append("| **All** | **").Append(coverage.Documented).Append("** | **").Append(coverage.Total)
            .Append("** | **").Append(Coverage.Percent(coverage.Documented, coverage.Total)).Append("** |\n\n");

        return page.ToString();
    }

    /// <summary>A summary in a table cell: one line, no pipes, no fences.</summary>
    private static string OneLine(string text)
    {
        if (text.Length == 0) return "*Undocumented.*";

        string flat = text.Replace("\r\n", " ").Replace('\n', ' ').Replace("|", "\\|");
        while (flat.Contains("  ", StringComparison.Ordinal)) flat = flat.Replace("  ", " ");
        return flat.Trim();
    }

    /// <summary>The anchor GitHub gives a heading, so the table of contents on each page works.</summary>
    public static string Anchor(string heading)
    {
        var anchor = new StringBuilder();
        foreach (char c in heading.ToLowerInvariant())
        {
            if (char.IsLetterOrDigit(c) || c == '-' || c == '_') anchor.Append(c);
            else if (c == ' ') anchor.Append('-');
        }

        return anchor.ToString();
    }
}
